### PR TITLE
Small change

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**

### CODE REVIEW

**Comment by gabrielvicenteYT** [comment]
@CzechHek This is the best pull request

**Comment by CzechHek** [comment]
I believe stopping should be forced, since some flys move very wildly and if you disabled Fly in a certain phase, you could easily get flagged.

However, I made some other small changes.

**Comment by gabrielvicenteYT** [comment]
> I believe stopping should be forced, since some flys move very wildly and if you disabled Fly in a certain phase, you could easily get flagged.
> 
> However, I made some other small changes.

How about for SmoothVanilla fly? AAC4 exists, hence why I made it toggleable

**Comment by gabrielvicenteYT** [comment]
> I believe stopping should be forced, since some flys move very wildly and if you disabled Fly in a certain phase, you could easily get flagged.
> 
> However, I made some other small changes.

Some anti-cheats flag that, so why not make it fully toggleable?

**Pull request closed without merging**
